title: My Portfolio
author: Andrew Raper
email: andrewraper.tx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is a portfolio of my work

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
